### PR TITLE
updated code to Python syntax

### PR DESCRIPTION
**Pull request by shilewenuw**

### CODE REVIEW

**Comment by jaredbroad** [comment]
100% this is an improvement, but I'm not sure it will compile, can you please test it?

**Comment by shilewenuw** [comment]
> 100% this is an improvement, but I'm not sure it will compile, can you please test it?

https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_58c39977ed18a1f26bb22e861c652071.html

**Comment by jaredbroad** [comment]
Thanks, Market=None and leverage=0 should not have worked -- mind buying something/testing really works in a real use case.

**Comment by shilewenuw** [comment]
> Thanks, Market=None and leverage=0 should not have worked -- mind buying something/testing really works in a real use case.

I didn't even notice that, I literally just translated the C# snippet the best I could

**Comment by jaredbroad** [comment]
Closing as example will not work - please resubmit with a realistic example

**Pull request closed without merging**
