### PR TITLE
docs: `defauls` -> `defaults`

### PR DESCRIPTION
**Pull request by ryanrussell**
Signed-off-by: Ryan Russell <git@ryanrussell.org>

#### Description
Global replace `defauls` -> `defaults`

#### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

**Review by jaredbroad — CHANGES_REQUESTED** [review]
Thank you for the PR! Please revert the HTML changes in the generated content and just make the python code generator change -- that script creates all the child HTML files.

**Comment by ryanrussell** [comment]
> Thank you for the PR! Please revert the HTML changes in the generated content and just make the python code generator change -- that script creates all the child HTML files.

So much cleaner!

Thanks for the patience while I'm ingesting the platform :)

**Comment by DerekMelchin** [comment]
Thanks @ryanrussell, but these html pages are generated by a script. The underlying typo is here:
https://github.com/QuantConnect/Documentation/blob/master/code-generators/Indicator-Reference-Code-Generator.py#L565

**Comment by ryanrussell** [comment]
> Thanks @ryanrussell, but these html pages are generated by a script. The underlying typo is here: https://github.com/QuantConnect/Documentation/blob/master/code-generators/Indicator-Reference-Code-Generator.py#L565

Hi @DerekMelchin -- Thanks for the feedback. I believe the changes were addressed in [83ce5fe](https://github.com/QuantConnect/Documentation/pull/772/commits/83ce5fedf2b2626587f7def2232c48a5f8fcd7bf)?

Files changed: https://github.com/QuantConnect/Documentation/pull/772/files

Let me know if it's easier just to close this out if it's too messy. We've spent a lot of characters talking about one :)

image

**Comment by DerekMelchin** [comment]
I see, thanks!

**Pull request merged**
