### PR TITLE
Improve Crypto Trading Examples

### LINKED ISSUE #949: Position Sizing for Crypto
#### Expected Behavior

We explain a workaround to position sizing a Crypto portfolio since we can't use SetHoldings. The [Crypto Trades](https://www.quantconnect.com/docs/v2/writing-algorithms/trading-and-orders/crypto-trades) page should provide lots of useful examples.

#### Actual Behavior

We don't explain an easy workaround

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

### PR DESCRIPTION
**Pull request by AlexCatarino**
#### Description
Improves crypto trading examples.
They are not a solution for all scenarios, but they are an improvement from current examples and give a better starting point.

#### Related Issue
Closes #949

### CODE REVIEW

**Comment by jaredbroad** [comment]
Please add section to show placing orders for cash accounts -- so the examples should retain an example of using the cashbook with crypto trading.

**Review by jaredbroad — CHANGES_REQUESTED** [review]
Cash account trading

**Comment by AlexCatarino** [comment]
The examples are for cash account as this line:
```csharp
var baseCurrency = crypto.BaseCurrency;
```
is equivalent to 
```csharp
self.Portfolio.CashBook['BTC']
```
The methods ensure we don't go negative. I developed this example using a Cash account.

**Review by jaredbroad — APPROVED** [review]

**Comment by jaredbroad** [comment]
Ty. It feels like we should throw if know it'll fail like a pre-order check. Especially for other tokens where there likely won't be tokens to buy-sell.

**Pull request merged**
